export { scanRepo } from "./scanRepo.js";
export type { ScanRepoOptions } from "./scanRepo.js";
export { status } from "./status.js";
export type { RepoStatus, StatusOptions } from "./status.js";
export { installHooks, uninstallHooks } from "./installHooks.js";
export type { InstallHooksOptions, HookInstallResult } from "./installHooks.js";
export { trackRepo, untrackRepo } from "./trackRepo.js";
export type { TrackRepoOptions } from "./trackRepo.js";
export { ConvosDataset } from "../core/dataset.js";
export type { ConversationListItem, ToolCallWithResult, VisibleMessage } from "../core/dataset.js";
export type { ConvosJsonlLineV1, ConvosProvider, QueryResult, QuerySupport } from "../core/schema/convos-jsonl-v1.js";
