import path from "node:path";
import { daysSince, formatAge } from "./time.js";
import type { DerivedThread, OverviewItem } from "./types.js";

export type RenderInput = {
  vaultRoot: string;
  derived: DerivedThread[];
  whyLines: Record<string, string>;
  unowned: OverviewItem[];
  now: Date;
};

const doNotEditComment = "<!-- tangent threads: generated by `tangent threads sweep`. Do not hand-edit; every sweep overwrites this file. -->";

const attentionStates = new Set(["blocked-on-you", "ready-for-you", "needs-you"]);

/** Urgency order within the combined "NEEDS YOU" section: an open question beats a fired timer beats a waiting deliverable. Exported so the sidecar's needsYou list sorts the same way. */
const attentionPriority: Record<string, number> = { "blocked-on-you": 0, "needs-you": 1, "ready-for-you": 2 };

/** Sorts derived threads most-urgent-first for both threads.md and the sidecar's needsYou list. */
export function compareByUrgency(a: DerivedThread, b: DerivedThread): number {
  return (attentionPriority[a.state] ?? 9) - (attentionPriority[b.state] ?? 9);
}

/**
 * Renders the generated threads.md view: one section per attention state (the design's combined
 * "NEEDS YOU" section covers blocked-on-you, needs-you, and ready-for-you; WORKING and PARKED get
 * their own sections), most-urgent-first, plus a trailing unowned backlog. Mirrors the vault's
 * existing do-not-hand-edit convention (plate.md).
 */
export function renderThreadsMarkdown(input: RenderInput): string {
  const { derived, whyLines, unowned, now } = input;
  const open = derived.filter((thread) => thread.state !== "done");
  const attention = open.filter((thread) => attentionStates.has(thread.state));
  const working = open.filter((thread) => thread.state === "working");
  const parked = open.filter((thread) => thread.state === "parked");

  const lines: string[] = [doNotEditComment, "", `${vaultLabel(input.vaultRoot)}  ${headerTimestamp(now)}`];
  lines.push(...renderSection("● NEEDS YOU", attention, whyLines, now));
  lines.push(...renderSection("◐ WORKING", working, whyLines, now));
  lines.push(...renderSection("◌ PARKED", parked, whyLines, now));
  lines.push(...renderUnownedSection(unowned));
  return `${lines.join("\n").trimEnd()}\n`;
}

/** Renders one attention/working/parked section as a header line plus one line per thread, most-urgent-first; returns no lines at all when the section is empty. */
function renderSection(title: string, threads: DerivedThread[], whyLines: Record<string, string>, now: Date): string[] {
  if (!threads.length) return [];
  const sorted = [...threads].sort(compareByUrgency);
  const lines = ["", `${title} (${threads.length})`];
  for (const thread of sorted) {
    const why = whyLines[thread.slug] || thread.templateWhy;
    const age = formatAge(daysSince(thread.openedAt, now));
    lines.push(`  ${thread.slug}  ${thread.owner}  ${why}  (${age})`);
  }
  return lines;
}

const wikiLink = /\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|([^\]]*))?\]\]/g;
const unownedMaxLines = 10;
const unownedMaxChars = 80;

/**
 * Renders the unowned backlog as one line per item (`  <node-basename>  <text>`), sorted by node
 * then text, capped at unownedMaxLines with a trailing "… and N more" summary. A single
 * dot-separated paragraph reads fine for a handful of items but is unreadable once a real vault's
 * backlog runs into the dozens, which is exactly the case that surfaced this.
 */
function renderUnownedSection(items: OverviewItem[]): string[] {
  if (!items.length) return [];
  const sorted = [...items].sort((a, b) => a.node.localeCompare(b.node) || a.text.localeCompare(b.text));
  const lines = ["", `⚠ UNOWNED (${items.length})`];
  for (const item of sorted.slice(0, unownedMaxLines)) {
    lines.push(`  ${nodeBasename(item.node)}  ${truncate(stripWikiLinks(item.text), unownedMaxChars)}`);
  }
  if (sorted.length > unownedMaxLines) lines.push(`  … and ${sorted.length - unownedMaxLines} more`);
  return lines;
}

/** Strips wiki-link syntax down to display text: `[[target|label]]` becomes `label`, `[[a/b/target]]` becomes `target`. */
function stripWikiLinks(text: string): string {
  return text.replace(wikiLink, (_match, target: string, label: string | undefined) => {
    if (label) return label;
    const segments = target.split("/");
    return segments[segments.length - 1] || target;
  });
}

/** Truncates text to maxChars total (including a trailing ellipsis when truncated). */
function truncate(text: string, maxChars: number): string {
  return text.length > maxChars ? `${text.slice(0, maxChars - 1)}…` : text;
}

/** The item's owning node, reduced to its last path segment for a compact backlog label. */
function nodeBasename(node: string): string {
  return path.basename(node) || "vault";
}

/** The header label: the vault root's own directory name, or "threads" as a fallback when that name is empty. */
function vaultLabel(root: string): string {
  return path.basename(root) || "threads";
}

/** Formats the header's "Wed 16 Jul, 17:40"-style timestamp in local time. */
function headerTimestamp(now: Date): string {
  const weekday = now.toLocaleDateString("en-US", { weekday: "short" });
  const day = now.getDate();
  const month = now.toLocaleDateString("en-US", { month: "short" });
  const hh = String(now.getHours()).padStart(2, "0");
  const mm = String(now.getMinutes()).padStart(2, "0");
  return `${weekday} ${day} ${month}, ${hh}:${mm}`;
}
