import path from "node:path";
import { daysSince, formatAge } from "./time.js";
import type { DerivedThread, OverviewItem, ThreadState, ViewItem, ViewThread } from "./types.js";

/**
 * The resolved render inputs: threads with their final why-lines already chosen, plus the unowned
 * backlog. This same shape is persisted in the sidecar (`SidecarState.view`) so `tangent threads
 * list <subtree>` can re-render a filtered tree without re-running a sweep.
 */
export type RenderInput = {
  vaultRoot: string;
  threads: ViewThread[];
  unowned: ViewItem[];
  now: Date;
  /** Subtree query the view was filtered by, shown in the header so a filtered view is self-describing. */
  filter?: string;
};

const doNotEditComment = "<!-- tangent threads: generated by `tangent threads sweep`. Do not hand-edit; every sweep overwrites this file. -->";

const attentionStates = new Set<ThreadState>(["blocked-on-you", "ready-for-you", "needs-you"]);

/** Urgency order within the "NEEDS YOU" strip: an open question beats a fired timer beats a waiting deliverable. Exported so the sidecar's needsYou list sorts the same way. */
const attentionPriority: Record<string, number> = { "blocked-on-you": 0, "needs-you": 1, "ready-for-you": 2 };

/** Sorts threads most-urgent-first for both the NEEDS YOU strip and the sidecar's needsYou list. */
export function compareByUrgency(a: { state: ThreadState }, b: { state: ThreadState }): number {
  return (attentionPriority[a.state] ?? 9) - (attentionPriority[b.state] ?? 9);
}

/** Maps derived threads plus their resolved why-lines (haiku or templated) and the unowned backlog into the persistable view shape the renderer consumes. The sweep stores exactly this in the sidecar so a later filtered `list` renders the same content. */
export function buildThreadsView(derived: DerivedThread[], whyLines: Record<string, string>, unowned: OverviewItem[]): { threads: ViewThread[]; unowned: ViewItem[] } {
  return {
    threads: derived
      .filter((thread) => thread.state !== "done")
      .map((thread) => ({
        slug: thread.slug,
        node: thread.node,
        owner: thread.owner,
        state: thread.state,
        why: whyLines[thread.slug] || thread.templateWhy,
        openedAt: thread.openedAt,
        batch: thread.batch
      })),
    unowned: unowned.map((item) => ({ node: item.node, text: stripWikiLinks(item.text) }))
  };
}

/**
 * Returns whether a node path matches a subtree query: the query's path segments must appear as a
 * contiguous run somewhere in the node's segments, so "neara" matches every node under neara/, and
 * "pgande" matches neara/pgande and all its descendants without the caller typing the full path.
 */
export function nodeMatchesSubtree(node: string, query: string): boolean {
  const trimmed = query.replace(/^\/+|\/+$/g, "");
  if (!trimmed) return true;
  const nodeSegments = node.split("/");
  const querySegments = trimmed.split("/");
  for (let start = 0; start + querySegments.length <= nodeSegments.length; start += 1) {
    if (querySegments.every((segment, offset) => nodeSegments[start + offset] === segment)) return true;
  }
  return false;
}

/** Filters a persisted view down to the nodes matching a subtree query (see nodeMatchesSubtree). */
export function filterViewBySubtree(view: { threads: ViewThread[]; unowned: ViewItem[] }, query: string): { threads: ViewThread[]; unowned: ViewItem[] } {
  return {
    threads: view.threads.filter((thread) => nodeMatchesSubtree(thread.node, query)),
    unowned: view.unowned.filter((item) => nodeMatchesSubtree(item.node, query))
  };
}

/**
 * Renders the generated threads.md view: a "NEEDS YOU" strip on top (most urgent first, the only
 * part that demands action), then every open thread and unowned backlog item organized as the
 * vault's node tree, so the file reads the way the vault is structured. Chains of nodes with no
 * content of their own collapse into one label (neara/pgande/), and top-level groups are separated
 * by a blank line. Mirrors the vault's existing do-not-hand-edit convention (plate.md).
 */
export function renderThreadsMarkdown(input: RenderInput): string {
  const open = input.threads.filter((thread) => thread.state !== "done");
  const attention = open.filter((thread) => attentionStates.has(thread.state));

  const label = input.filter ? `${vaultLabel(input.vaultRoot)}/${input.filter.replace(/^\/+|\/+$/g, "")}` : vaultLabel(input.vaultRoot);
  const lines: string[] = [doNotEditComment, "", `${label}  ${headerTimestamp(input.now)}`];

  if (attention.length) {
    lines.push("", `● NEEDS YOU (${attention.length})`);
    for (const thread of [...attention].sort(compareByUrgency)) {
      lines.push(`  ${threadLineBody(thread, input.now)}`);
    }
  }

  const tree = buildNodeTree(open, input.unowned);
  if (tree.children.size === 0 && tree.threads.length === 0 && tree.unowned.length === 0) {
    lines.push("", input.filter ? `(nothing under ${input.filter})` : "(no open threads or backlog)");
  } else {
    lines.push(...renderNodeItems(tree, 0, input.now));
    lines.push(...renderNodeChildren(tree, 0, input.now, true));
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** One node of the render tree: child nodes by path segment plus this node's own threads and unowned items. */
type NodeTreeNode = {
  children: Map<string, NodeTreeNode>;
  threads: ViewThread[];
  unowned: ViewItem[];
};

/** Creates an empty render-tree node. */
function emptyNode(): NodeTreeNode {
  return { children: new Map(), threads: [], unowned: [] };
}

/** Builds the node tree from every open thread's and unowned item's vault-relative node path. Root-level items (node "") land on the returned root node itself. */
function buildNodeTree(threads: ViewThread[], unowned: ViewItem[]): NodeTreeNode {
  const root = emptyNode();
  /** Walks (creating as needed) to the tree node for a vault-relative node path. */
  const nodeAt = (nodePath: string): NodeTreeNode => {
    if (!nodePath) return root;
    let current = root;
    for (const segment of nodePath.split("/")) {
      let child = current.children.get(segment);
      if (!child) {
        child = emptyNode();
        current.children.set(segment, child);
      }
      current = child;
    }
    return current;
  };
  for (const thread of threads) nodeAt(thread.node).threads.push(thread);
  for (const item of unowned) nodeAt(item.node).unowned.push(item);
  return root;
}

/** Sort order for a node's own thread lines: attention first (by urgency), then working, then parked. */
const stateOrder: Record<string, number> = { "blocked-on-you": 0, "needs-you": 1, "ready-for-you": 2, finishing: 3, working: 4, parked: 5 };

/** Sentinel batch key sorting after every real batch name, so unbatched working threads settle after batch groups instead of splitting them up. */
const noBatchSortKey = "￿";

/** Sorts one node's threads: by state urgency, then batch group, then slug. */
function compareNodeThreads(a: ViewThread, b: ViewThread): number {
  const stateDelta = (stateOrder[a.state] ?? 9) - (stateOrder[b.state] ?? 9);
  if (stateDelta) return stateDelta;
  const aBatch = a.batch ?? noBatchSortKey;
  const bBatch = b.batch ?? noBatchSortKey;
  return aBatch.localeCompare(bBatch) || a.slug.localeCompare(b.slug);
}

const stateIcon: Record<string, string> = {
  "blocked-on-you": "●",
  "needs-you": "●",
  "ready-for-you": "●",
  finishing: "◑",
  working: "◐",
  parked: "◌"
};

/** Renders a node's child subtrees, collapsing label chains (a child with no items of its own and exactly one child renders as "parent/child/"). Top-level groups get a preceding blank line. */
function renderNodeChildren(node: NodeTreeNode, depth: number, now: Date, topLevel: boolean): string[] {
  const lines: string[] = [];
  for (const name of [...node.children.keys()].sort()) {
    let label = name;
    let child = node.children.get(name)!;
    while (child.threads.length === 0 && child.unowned.length === 0 && child.children.size === 1) {
      const [nextName, nextChild] = [...child.children.entries()][0]!;
      label = `${label}/${nextName}`;
      child = nextChild;
    }
    if (topLevel) lines.push("");
    lines.push(`${indent(depth)}${label}/`);
    lines.push(...renderNodeItems(child, depth + 1, now));
    lines.push(...renderNodeChildren(child, depth + 1, now, false));
  }
  return lines;
}

/** Renders one node's own thread and unowned lines, threads first (sorted by compareNodeThreads), unowned sorted by text. */
function renderNodeItems(node: NodeTreeNode, depth: number, now: Date): string[] {
  const lines: string[] = [];
  for (const thread of [...node.threads].sort(compareNodeThreads)) {
    lines.push(`${indent(depth)}${stateIcon[thread.state] ?? "◌"} ${threadLineBody(thread, now)}`);
  }
  for (const item of [...node.unowned].sort((a, b) => a.text.localeCompare(b.text))) {
    lines.push(`${indent(depth)}⚠ ${truncate(item.text, unownedMaxChars)}`);
  }
  return lines;
}

/** The shared "slug  owner  why  (age)" body of a thread line, with the why prefixed by its batch name when it has one. */
function threadLineBody(thread: ViewThread, now: Date): string {
  const why = thread.batch ? `[${thread.batch}] ${thread.why}` : thread.why;
  const age = formatAge(daysSince(thread.openedAt, now));
  return `${thread.slug}  ${thread.owner}  ${why}  (${age})`;
}

/** Two spaces per tree depth. */
function indent(depth: number): string {
  return "  ".repeat(depth);
}

const wikiLink = /\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|([^\]]*))?\]\]/g;
const unownedMaxChars = 80;

/** Strips wiki-link syntax down to display text: `[[target|label]]` becomes `label`, `[[a/b/target]]` becomes `target`. */
function stripWikiLinks(text: string): string {
  return text.replace(wikiLink, (_match, target: string, label: string | undefined) => {
    if (label) return label;
    const segments = target.split("/");
    return segments[segments.length - 1] || target;
  });
}

/** Truncates text to maxChars total (including a trailing ellipsis when truncated). */
function truncate(text: string, maxChars: number): string {
  return text.length > maxChars ? `${text.slice(0, maxChars - 1)}…` : text;
}

/** The header label: the vault root's own directory name, or "threads" as a fallback when that name is empty. */
function vaultLabel(root: string): string {
  return path.basename(root) || "threads";
}

/** Formats the header's "Wed 16 Jul, 17:40"-style timestamp in local time. */
function headerTimestamp(now: Date): string {
  const weekday = now.toLocaleDateString("en-US", { weekday: "short" });
  const day = now.getDate();
  const month = now.toLocaleDateString("en-US", { month: "short" });
  const hh = String(now.getHours()).padStart(2, "0");
  const mm = String(now.getMinutes()).padStart(2, "0");
  return `${weekday} ${day} ${month}, ${hh}:${mm}`;
}
